### PR TITLE
Fix color browser elements

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
See https://goo.gl/oetGgf and https://goo.gl/8viLMX for more info.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@samdutton I know very little about those meta tags, could you PTAL?

**Comment by samdutton** [comment]
I added these tags — the proposed change looks fine to me, but not sure what the point is of changing the theme colour from white to grey.

**Comment by FluorescentHallucinogen** [comment]
Compare the screenshots before and after applying the patch.

Before:

Before

After:

After

**Comment by samdutton** [comment]
@KaptenJansson WDYT? I don't object to changing the colour, but not sure which is best.

**Comment by KaptenJansson** [comment]
My monitor must be bad at representing those colors, I see no difference between the screenshots.

**Comment by KaptenJansson** [comment]
Ow it's the top bar, I see ;) Well LGTM, I do not mind either way.

**Comment by FluorescentHallucinogen** [comment]
@samdutton, @KaptenJansson, could you please merge this pull request (and update the files deployed at https://appr.tc to reflect the recent changes in git)?

**Comment by KaptenJansson** [comment]
Sure

**Pull request merged**
