### PR TITLE
Updated the room.py log for clarity

### PR DESCRIPTION
**Pull request by wzh--**
@chuckhays PTAL

### CODE REVIEW

**Comment by chuckhays** [comment]
LGTM.

**Comment by milkypostman** [comment]
Couldn't all these be a bit more concise like,

`'remove_room_direct: ' + client_gcm_id + ' not in room ' + room_id`

I'm happy to take a stab at it.

@wzh-- normally you should squash these commits and force push to your branch. I can show you how in person if you want to know but you have to make sure you're pushing to your repo and not the apprtc one :smiling_imp:

**Comment by milkypostman** [comment]
Or it could be,

`'Can\'t remove room: ' + client_gcm_id + ' not in room ' + room_id`

Anyways, just a suggestion.

**Comment by chuckhays** [comment]
I think we need to do some logging work overall to standardize what we report and how/where, probably building on what you've done @milkypostman.

**Comment by wzh--** [comment]
@milkypostman it'd be great if you can show me how to squash these commits, when you have time. thx.

**Comment by wzh--** [comment]
@milkypostman @chuckhays Chuck showed me how to do it. Thanks.

**Comment by wzh--** [comment]
Merge the quick fix for now. It's useful for the client/server debugging. As @chuckhays said, a more complete solution might be needed for a clean logging.

**Pull request merged**
