### PR TITLE
Fix version_info.json path so app engine can be run locally.

### PR DESCRIPTION
**Pull request by tkchin**
Port of:
0e96764799c1613ed3ed0596082bf390dea153c2

### CODE REVIEW

**Comment by tkchin** [comment]
@jiayliu PTAL

Turns out my local app engine instance wouldn't load correctly without this.

**Comment by milkypostman** [comment]
what is the error? you're running `dev_appserver.py out/app_engine`?

**Comment by jiayliu** [comment]
lgtm

**Comment by tkchin** [comment]
I'm using the GoogleAppEngineLauncher tool on the out/app_engine dir. Logs here:

INFO     2015-02-13 22:29:02,932 apprtc.py:86] Applying media constraints: {'audio': True, 'video': {'mandatory': {}, 'optional': [{'minWidth': '1280'}, {'minHeight': '720'}]}}
ERROR    2015-02-13 22:29:02,932 webapp2.py:1528] [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 515, in get
    params = get_room_parameters(self.request, None, None, None)
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 262, in get_room_parameters
    'version_info': json.dumps(get_version_info())
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 133, in get_version_info
    f = open('version_info.json')
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 249, in __init__
    if not FakeFile.is_file_accessible(filename):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 220, in is_file_accessible
    fixed_filename = os.path.normcase(os.path.abspath(filename))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 356, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
ERROR    2015-02-13 22:29:02,934 wsgi.py:279] 
Traceback (most recent call last):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/runtime/wsgi.py", line 267, in Handle
    result = handler(dict(self._environ), self._StartResponse)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1519, in __call__
    response = self._internal_error(e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/lib/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 515, in get
    params = get_room_parameters(self.request, None, None, None)
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 262, in get_room_parameters
    'version_info': json.dumps(get_version_info())
  File "/Users/tkchin/src/tkchin_apprtc/out/app_engine/apprtc.py", line 133, in get_version_info
    f = open('version_info.json')
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 249, in __init__
    if not FakeFile.is_file_accessible(filename):
  File "/Applications/GoogleAppEngineLauncher.app/Contents/Resources/GoogleAppEngine-default.bundle/Contents/Resources/google_appengine/google/appengine/tools/devappserver2/python/stubs.py", line 220, in is_file_accessible
    fixed_filename = os.path.normcase(os.path.abspath(filename))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 356, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
INFO     2015-02-13 22:29:02,941 module.py:718] default: "GET / HTTP/1.1" 500 -
INFO     2015-02-13 22:29:03,217 module.py:391] [default] Detected file changes:
  /Users/tkchin/src/tkchin_apprtc/out/app_engine/third_party/apiclient
  /Users/tkchin/src/tkchin_apprtc/out/app_engine/third_party/httplib2
  /Users/tkchin/src/tkchin_apprtc/out/app_engine/third_party/oauth2client
  /Users/tkchin/src/tkchin_apprtc/out/app_engine/third_party/uritemplate

**Pull request merged**
