### PR TITLE
Delay usage of AppAssertionCredentials

### PR DESCRIPTION
**Pull request by milkypostman**
This should avoid some import problems on the test servers related to
issue #21.

### CODE REVIEW

**Comment by phoglund** [comment]
Where does the secrets.json normally come from? If I clone this repo and run grunt build, will the secrets.json be there or does it need to be copied in as a separate step?

**Comment by milkypostman** [comment]
@phoglund you have to run `grunt build` and then all that stuff is built.

previously you could run it directly from the appengine directory (sans javascript being compiled with `grunt build`) but now you have to build all of it.

**Comment by chuckhays** [comment]
LGTM.

**Comment by phoglund** [comment]
Ok. My point is we need some way to bring up the server on the bots without importing the stuff that broke the bots before (e.g SignedJwtSomething). The bots do build using grunt build. Will this patch solve that or do we need to add a app.yaml flag the bots can override?

**Comment by milkypostman** [comment]
@phoglund how are you running the server on the bots? If you are using `dev_appserver.py` then it should just work. The problem was the import and now the actual object that was being imported should never be used. When running `dev_appserver.py` we look for `secrets.json` and if it's not there then we just do logging to stdout. The only time this would fail is if it was running *on* AppEngine.

**Comment by phoglund** [comment]
It does use dev_appserver, but the problem was the crypto libraries were too old on the bot, but not on our workstations.

To test this, go into the google_appengine SDK you're launching from. Edit google_appengine/oauth2client/client.py. Go to line 44 or thereabouts and change the line HAS_CRYPTO = True to HAS_CRYPTO = False. Run your code with google_appengine/dev_appserver.py path/to/checkout/out/app_engine and ensure you can still get a call up on that server.

If that still works you're good. Remember to change back the HAS_CRYPTO line later :)

**Comment by milkypostman** [comment]
It works. Since it's very late here I will merge this tomorrow when I get in.

**Pull request merged**
