### PR TITLE
Add a websocket read timeout to temporarily fix socket leak

### PR DESCRIPTION
**Pull request by jiayliu**

### CODE REVIEW

**Comment by jiayliu** [comment]
Zeke, PTAL

**Comment by tkchin** [comment]
lgtm

This looks right given we had errors on 443. Is it possible to write a stress test unit test to check the fix? Probably good to get this in so we can fix error, but if it doesn't take long to write might as well add it.

**Comment by jiayliu** [comment]
The real problem is found and fixed in the new patch. PTAL

**Comment by milkypostman** [comment]
LGTM.

**Comment by tkchin** [comment]
sweet, lgtm

**Pull request merged**
