### PR TITLE
Revert "Add the AnalyticsPage to AppRTC."

### PR DESCRIPTION
**Pull request by jiayliu**
Reverts webrtc/apprtc#63
Travis failed: https://travis-ci.org/webrtc/apprtc/builds

### CODE REVIEW

**Comment by jiayliu** [comment]
@milkypostman

**Comment by milkypostman** [comment]
@tkchin did something change in the last day that would cause something in the build to not be setting up the paths properly. I don't understand what is happening with this. third_party is setup properly in the build but now for some reason it's failing. It wasn't when I authored the CL.

**Comment by jiayliu** [comment]
This is the error:


======================================================================

ERROR: apprtc_test (unittest.loader.ModuleImportFailure)

----------------------------------------------------------------------

ImportError: Failed to import test module: apprtc_test

Traceback (most recent call last):

  File "/usr/lib/python2.7/unittest/loader.py", line 252, in _find_tests

    module = self._get_module_from_name(name)

  File "/usr/lib/python2.7/unittest/loader.py", line 230, in
_get_module_from_name

    __import__(name)

  File "/home/travis/build/webrtc/apprtc/out/app_engine/apprtc_test.py",
line 10, in <module>

    import analytics

  File "/home/travis/build/webrtc/apprtc/out/app_engine/analytics.py",
line 14, in <module>

    import apiauth

  File "/home/travis/build/webrtc/apprtc/out/app_engine/apiauth.py",
line 11, in <module>

    from apiclient import discovery

  File "/home/travis/build/webrtc/apprtc/out/app_engine/third_party/apiclient/discovery.py",
line 52, in <module>

    from apiclient.errors import HttpError

  File "/home/travis/build/webrtc/apprtc/out/app_engine/third_party/apiclient/errors.py",
line 27, in <module>

    from oauth2client.anyjson import simplejson

ImportError: No module named anyjson


On Fri, Feb 20, 2015 at 9:41 AM, Donald Ephraim Curtis <
notifications@github.com> wrote:

> @tkchin <https://github.com/tkchin> did something change in the last day
> that would cause something in the build to not be setting up the paths
> properly. I don't understand what is happening with this. third_party is
> setup properly in the build but now for some reason it's failing. It wasn't
> when I authored the CL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/pull/86#issuecomment-75284920>.
>



-- 
Jiayang Liu

**Comment by milkypostman** [comment]
:) i see that but before I pushed the changes I ran the python tests and they worked fine. now all of a sudden today it's not even working on that branch.

**Comment by milkypostman** [comment]
I mean, you can see it here: https://travis-ci.org/webrtc/apprtc/builds/51291408

Running tests on the same commit today causes issues. It's bonkers.

**Comment by jiayliu** [comment]
But there is no other commit between success and failure builds...

On Fri, Feb 20, 2015 at 9:47 AM, Donald Ephraim Curtis <
notifications@github.com> wrote:

> I mean, you can see it here:
> https://travis-ci.org/webrtc/apprtc/builds/51291408
>
> Running tests on the same commit today causes issues. It's bonkers.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/webrtc/apprtc/pull/86#issuecomment-75286005>.
>



-- 
Jiayang Liu

**Comment by jiayliu** [comment]
Eh, now it has a bigger problem:

3.13s$ git fetch origin +refs/pull/86/merge:
fatal: Couldn't find remote ref refs/pull/86/merge
The command "eval git fetch origin +refs/pull/86/merge:" failed. Retrying,
2 of 3.
fatal: Couldn't find remote ref refs/pull/86/merge
The command "eval git fetch origin +refs/pull/86/merge:" failed. Retrying,
3 of 3.
fatal: Couldn't find remote ref refs/pull/86/merge
The command "eval git fetch origin +refs/pull/86/merge:" failed 3 times.
The command "git fetch origin +refs/pull/86/merge:" failed and exited with
128 during .
Your build has been stopped.



On Fri, Feb 20, 2015 at 9:49 AM, Jiayang Liu <jiayl@google.com> wrote:

> But there is no other commit between success and failure builds...
>
> On Fri, Feb 20, 2015 at 9:47 AM, Donald Ephraim Curtis <
> notifications@github.com> wrote:
>
>> I mean, you can see it here:
>> https://travis-ci.org/webrtc/apprtc/builds/51291408
>>
>> Running tests on the same commit today causes issues. It's bonkers.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/webrtc/apprtc/pull/86#issuecomment-75286005>.
>>
>
>
>
> --
> Jiayang Liu
>



-- 
Jiayang Liu

**Comment by jiayliu** [comment]
I revert the revert, and the git fetch error is gone.

Verified locally that reverting Donald's change does not fix the error.

On Fri, Feb 20, 2015 at 9:56 AM, Jiayang Liu <jiayl@google.com> wrote:

> Eh, now it has a bigger problem:
>
> 3.13s$ git fetch origin +refs/pull/86/merge:
> fatal: Couldn't find remote ref refs/pull/86/merge
> The command "eval git fetch origin +refs/pull/86/merge:" failed. Retrying,
> 2 of 3.
> fatal: Couldn't find remote ref refs/pull/86/merge
> The command "eval git fetch origin +refs/pull/86/merge:" failed. Retrying,
> 3 of 3.
> fatal: Couldn't find remote ref refs/pull/86/merge
> The command "eval git fetch origin +refs/pull/86/merge:" failed 3 times.
> The command "git fetch origin +refs/pull/86/merge:" failed and exited with
> 128 during .
> Your build has been stopped.
>
>
>
> On Fri, Feb 20, 2015 at 9:49 AM, Jiayang Liu <jiayl@google.com> wrote:
>
>> But there is no other commit between success and failure builds...
>>
>> On Fri, Feb 20, 2015 at 9:47 AM, Donald Ephraim Curtis <
>> notifications@github.com> wrote:
>>
>>> I mean, you can see it here:
>>> https://travis-ci.org/webrtc/apprtc/builds/51291408
>>>
>>> Running tests on the same commit today causes issues. It's bonkers.
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/webrtc/apprtc/pull/86#issuecomment-75286005>.
>>>
>>
>>
>>
>> --
>> Jiayang Liu
>>
>
>
>
> --
> Jiayang Liu
>



-- 
Jiayang Liu

**Pull request merged**
