### PR TITLE
Add support fordatachannel

### PR DESCRIPTION
**Pull request by hekra01**
**Description**
Add support for datachannel.
Related to
* https://github.com/njovy/AppRTCDemo/pull/32
* https://bugs.chromium.org/p/webrtc/issues/detail?id=6647

**Purpose**
Will enable to send text message for example.

### CODE REVIEW

**Comment by KaptenJansson** [comment]
@samdutton @juberti what's your opinion on adding data channels to AppRTC? Note that this does not include an UI or anything so more work would be needed for this to be usable by normal users.

**Comment by KaptenJansson** [comment]
@samdutton @juberti ping

**Comment by samdutton** [comment]
For chat?

On 2 Dec 2016 9:36 a.m., "Christoffer Jansson" <notifications@github.com>
wrote:

@samdutton <https://github.com/samdutton> @juberti
<https://github.com/juberti> ping

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/webrtc/apprtc/pull/389#issuecomment-264412355>, or mute
the thread

**Comment by hekra01** [comment]
Yes, chat is one use case. Could also be used for file transfer etc...

**Comment by KaptenJansson** [comment]
I think then dataChannel should only be setup when one of the features are enabled/requested however that will require renegotiation off course which AppRTC does not currently handle.

**Comment by KaptenJansson** [comment]
Closing. A followup PR with datachannel and a feature that uses it (e.g chat with a UI etc) will be considered.

**Pull request closed without merging**
