### PR TITLE
Merge changes from master

### PR DESCRIPTION
**Pull request by tkchin**
@jiayliu @milkypostman PTAL

Unit tests pass and open room connects. Most of the conflicts were analytics related, let me know if I missed anything.

### CODE REVIEW

**Comment by tkchin** [comment]
FYI 871c1a3b9fb46ab9daa03aa1ff4de50fe82e4abf has the list of files with conflicts.

**Comment by milkypostman** [comment]
will take a look this afternoon in more detail, but it looks like it makes sense :)

**Comment by tkchin** [comment]
Ok lmk. Can't run UTs anymore in this branch due to to API auth thing we ran into until this merge goes in, which blocks any other CLs on this branch.

**Comment by milkypostman** [comment]
The only weird thing I see is that we now have `test_uti.py` and `test_utilities.py`. I'm fine with this as it will make future commits easier to merge.

It's a bit hard to decrypt this but I checked that the things I added directly to `apprtc.py` were in the appropriate area after merge and all other files were the same.

LGTM

**Comment by tkchin** [comment]
Thanks for looking! Will merge if direct calling scenario works.

**Pull request merged**
